# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s = "Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
a = d['k1'][3]['tricky'][3]['target'][3] 
print(a) 

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [4]:
import numpy as np
array = np.zeros(10)
print(array) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
import numpy as np
array = np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [6]:
import numpy as np
array = np.arange(20, 35, 2)
print(array) 

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
import numpy as np
array = np.arange(0,9).reshape(3,3) 
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [8]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
array = np.concatenate((a,b))
print(array) 

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [9]:
import pandas as pd
a = [[0,1],[2,3],[4,5]]
df = pd.DataFrame(a)
print(df) 

   0  1
0  0  1
1  2  3
2  4  5


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [10]:
def gen_days(year):
  start_date = datetime(year,1,1)
  end_date = datetime(year,2,10)
  d = start_date
  dates = [start_date]
  while d < end_date:
    d += timedelta(days=1)
    dates.append(d)
  return dates

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [11]:
import pandas as pd 
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
